<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.1"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>174b2dd0-92fd-42f5-8487-4c3e6e90634c</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.1"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Example.ApiGateway\Example.ApiGateway.csproj" />
      <ProjectReference Include="..\Example.IdentityService\Example.IdentityService.csproj" />
      <ProjectReference Include="..\Example.WorkerService\Example.WorkerService.csproj" />
    </ItemGroup>

</Project>
